DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` INTEGER NOT NULL PRIMARY KEY,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL
);

INSERT INTO `users` (`name`, `email`)
VALUES
  ("Ivy Quinn", "lorem.eget@outlook.couk"),
  ("Alfonso Hodge", "ut.tincidunt@hotmail.com"),
  ("Arthur Buchanan", "enim.gravida@icloud.com"),
  ("Boris Raymond", "turpis.nulla@aol.couk"),
  ("Brent Mcpherson", "felis@aol.net"),
  ("Carol Lawrence", "vel.lectus@yahoo.org"),
  ("Cedric Rush", "massa.integer@aol.couk"),
  ("Zane Estes", "nunc.ac@yahoo.edu"),
  ("Idona Hewitt", "nunc.laoreet.lectus@yahoo.net"),
  ("Kylie Gardner", "quisque@google.net"),
  ("Garth Sherman", "in.faucibus@hotmail.ca"),
  ("Nero Cardenas", "ornare@hotmail.net"),
  ("Veda Acevedo", "nunc.sed.orci@yahoo.edu"),
  ("Ava Adams", "rhoncus.id@protonmail.net"),
  ("Shellie Joseph", "ante.blandit.viverra@google.net"),
  ("Garrison Cleveland", "lacus.cras.interdum@google.couk"),
  ("Rose Fischer", "parturient.montes@aol.couk"),
  ("Graiden Winters", "porttitor.eros.nec@yahoo.org"),
  ("Libby Ross", "nullam.vitae@google.net"),
  ("Camilla Knapp", "donec.est@protonmail.net"),
  ("Ezra Cotton", "neque@protonmail.org"),
  ("Elliott O'connor", "non.sapien@hotmail.net"),
  ("Colette Hurst", "nisl.elementum@protonmail.ca"),
  ("Nyssa Jefferson", "mi@google.edu"),
  ("Fuller Hood", "duis.gravida.praesent@hotmail.ca"),
  ("Chase Anthony", "integer.tincidunt@outlook.org"),
  ("Kiona Herrera", "ipsum.dolor.sit@hotmail.com"),
  ("Dara Yang", "libero.et@aol.com"),
  ("Brett Aguirre", "pellentesque.habitant@protonmail.couk"),
  ("Belle Schneider", "nunc.interdum@hotmail.ca"),
  ("Ria Calhoun", "cursus.vestibulum@icloud.org"),
  ("Hiram Boyle", "eget.laoreet@aol.org"),
  ("Galvin Lyons", "sed.dictum@google.couk"),
  ("Lenore Ortiz", "sed@icloud.org"),
  ("Sade Abbott", "sit.amet.luctus@protonmail.ca"),
  ("Dennis Wilder", "cursus.et@icloud.couk"),
  ("Malik Dunn", "eu.sem.pellentesque@yahoo.com"),
  ("Jelani Summers", "quisque.fringilla@hotmail.edu"),
  ("Myra Christian", "eu.dui.cum@protonmail.net"),
  ("Idola Cleveland", "imperdiet.erat@icloud.com"),
  ("Pascale Camacho", "ligula.consectetuer@hotmail.net"),
  ("Fleur Bryan", "nullam.lobortis@google.org"),
  ("Edward Marquez", "molestie.sed.id@icloud.net"),
  ("MacKensie Tran", "iaculis@icloud.couk"),
  ("Wilma Mccarty", "vulputate.nisi.sem@yahoo.couk"),
  ("Lunea Suarez", "montes.nascetur.ridiculus@icloud.edu"),
  ("Thaddeus Sears", "vel@yahoo.edu"),
  ("Trevor Dean", "phasellus@protonmail.edu"),
  ("Cara Keith", "natoque@protonmail.ca"),
  ("Paki Daniels", "sit.amet.orci@hotmail.com");

INSERT INTO `users` (`name`,`email`)
VALUES
  ("Nathan Frank", "adipiscing@yahoo.couk"),
  ("Aurora Dominguez", "porttitor.tellus.non@icloud.net"),
  ("Carter Hodge", "erat.in.consectetuer@yahoo.net"),
  ("Hayes Abbott", "arcu.vestibulum@hotmail.ca"),
  ("Robert Roman", "ut.tincidunt.orci@google.couk"),
  ("Nichole Lyons", "tincidunt.donec.vitae@google.couk"),
  ("Stone Hendrix", "et@yahoo.net"),
  ("Renee Middleton", "orci.sem.eget@aol.net"),
  ("Tanner Winters", "class.aptent@aol.org"),
  ("Armando Watts", "dis.parturient@hotmail.edu"),
  ("Lee Hutchinson", "cras@icloud.net"),
  ("Orla Bradford", "tortor.integer.aliquam@icloud.org"),
  ("Lawrence Munoz", "nec@aol.org"),
  ("Audra Burnett", "lacinia.orci@aol.couk"),
  ("Whoopi Mcbride", "augue.ut@icloud.edu"),
  ("Akeem Meadows", "cursus.et.magna@google.net"),
  ("Laurel Carney", "aliquam.auctor.velit@icloud.com"),
  ("Joseph Cherry", "ut.erat@google.ca"),
  ("Kane Cook", "orci.consectetuer@protonmail.couk"),
  ("Orson Curtis", "suspendisse.aliquet@outlook.edu"),
  ("Gail Collins", "augue.id@hotmail.com"),
  ("Jonas Abbott", "arcu.curabitur@protonmail.edu"),
  ("Morgan Cox", "ipsum@aol.couk"),
  ("Nyssa Wiggins", "dolor.sit.amet@protonmail.edu"),
  ("Fulton Ewing", "nec@aol.org"),
  ("Lydia Robertson", "dictum.placerat.augue@icloud.net"),
  ("Dane Petty", "donec@aol.edu"),
  ("Francis Wilkins", "eleifend.egestas@yahoo.couk"),
  ("Slade Barton", "a.malesuada@aol.net"),
  ("Willow Gentry", "sed@yahoo.ca"),
  ("Raphael Graves", "dis.parturient@icloud.couk"),
  ("Wyoming Bates", "adipiscing.elit@yahoo.ca"),
  ("Sonya Sherman", "felis.orci.adipiscing@hotmail.org"),
  ("Josephine Little", "est.vitae@aol.net"),
  ("Rose Shepherd", "elementum.lorem.ut@aol.org"),
  ("Jessamine Kidd", "amet.consectetuer@aol.org"),
  ("Mary Brooks", "amet.orci.ut@google.ca"),
  ("Jack Acevedo", "vestibulum.neque@outlook.ca"),
  ("Chastity Kim", "nunc@protonmail.couk"),
  ("Robert Herrera", "integer@outlook.edu"),
  ("Garth Larson", "molestie@aol.com"),
  ("Brandon Estrada", "orci.consectetuer@google.com"),
  ("Francesca Benson", "lacus.cras@aol.couk"),
  ("Clare Bush", "quisque.imperdiet.erat@hotmail.com"),
  ("Henry Vaughn", "ligula@aol.org"),
  ("Imani Newman", "sociis.natoque@aol.org"),
  ("Levi Sellers", "tristique.senectus@outlook.ca"),
  ("Zena Chase", "conubia.nostra@aol.ca"),
  ("Karen Quinn", "nonummy.fusce@yahoo.com"),
  ("Kylan Wong", "purus.in@outlook.couk");
